/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller;
import model.StringDinamica;

/**
 *
 * @author Willian
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextEditor = new javax.swing.JTextArea();
        TextFieldEditor = new javax.swing.JTextField();
        ButtonInserir = new javax.swing.JButton();
        ButtonApagar = new javax.swing.JButton();
        CheckInserirEspaco = new javax.swing.JCheckBox();
        CheckQuebraDeLinha = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        MenuArquivo = new javax.swing.JMenu();
        ButtonLocalizar = new javax.swing.JMenuItem();
        ButtonSair = new javax.swing.JMenuItem();
        MenuSobre = new javax.swing.JMenu();
        ButtonSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editor de texto");

        TextEditor.setColumns(20);
        TextEditor.setRows(5);
        jScrollPane1.setViewportView(TextEditor);

        TextFieldEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldEditorActionPerformed(evt);
            }
        });

        ButtonInserir.setText("Inserir");
        ButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInserirActionPerformed(evt);
            }
        });

        ButtonApagar.setText("Apagar");

        CheckInserirEspaco.setText("Inserir espaço");

        CheckQuebraDeLinha.setText("Quebra de linha");

        jLabel1.setText("Automatização");

        MenuArquivo.setText("Arquivo");

        ButtonLocalizar.setText("Localizar");
        ButtonLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLocalizarActionPerformed(evt);
            }
        });
        MenuArquivo.add(ButtonLocalizar);

        ButtonSair.setText("Sair");
        ButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSairActionPerformed(evt);
            }
        });
        MenuArquivo.add(ButtonSair);

        Menu.add(MenuArquivo);

        MenuSobre.setText("Sobre");

        ButtonSobre.setText("Sobre");
        ButtonSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSobreActionPerformed(evt);
            }
        });
        MenuSobre.add(ButtonSobre);

        Menu.add(MenuSobre);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldEditor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonInserir, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonApagar, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(CheckInserirEspaco)
                            .addComponent(CheckQuebraDeLinha))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonInserir, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(ButtonApagar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckInserirEspaco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckQuebraDeLinha)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldEditorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldEditorActionPerformed

    private void ButtonLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLocalizarActionPerformed
        // TODO add your handling code here:
        Localizar localizar = new Localizar();
        localizar.setVisible(true);
    }//GEN-LAST:event_ButtonLocalizarActionPerformed

    private void ButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ButtonSairActionPerformed

    private void ButtonSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSobreActionPerformed
        // TODO add your handling code here:
        new Sobre().setVisible(true);
    }//GEN-LAST:event_ButtonSobreActionPerformed

    private void ButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInserirActionPerformed
        // TODO add your handling code here:
        Controller.getInstance().converterString(TextFieldEditor.getText(), CheckInserirEspaco.isSelected(), CheckQuebraDeLinha.isSelected());
    }//GEN-LAST:event_ButtonInserirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
        System.out.println("""
                           Estrutura de dados 1
                           Trabalho semestral da disciplina
                           Editor de texto em Java com estrutura de dados para formar strings
                           """);
        System.out.println("Criado");
        StringDinamica dinamica = new StringDinamica();
        dinamica.insert(dinamica, 'a');
        dinamica.insert(dinamica, 'b');
        dinamica.insert(dinamica, 'c');
        dinamica.insert(dinamica, 'd');
        dinamica.insert(dinamica, 'e');
        dinamica.printList(dinamica);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonApagar;
    private javax.swing.JButton ButtonInserir;
    private javax.swing.JMenuItem ButtonLocalizar;
    private javax.swing.JMenuItem ButtonSair;
    private javax.swing.JMenuItem ButtonSobre;
    private javax.swing.JCheckBox CheckInserirEspaco;
    private javax.swing.JCheckBox CheckQuebraDeLinha;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu MenuArquivo;
    private javax.swing.JMenu MenuSobre;
    private javax.swing.JTextArea TextEditor;
    private javax.swing.JTextField TextFieldEditor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
